---
- name: create directory
  become: yes
  file:
    path: /home/app
    state: directory
    mode: 0755

- name: copy artifact to app directory
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/app/artifact.tar.gz

- name: uncompress
  become: yes
  shell: |
    cd /home/app
    tar -vxf artifact.tar.gz
- name: build and start node
  shell: |
    cd /home/app
    npm install
    pm2 stop default
    pm2 start npm -- start
  environment:
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
